export enum POLLING_INTERVAL {
  FiveSeconds = 5000,
  TenSeconds = 10000,
}

export enum PropertyCategory {
  BASIC = "CONNECTION",
  ADVANCED_GENERAL = "CONNECTION_ADVANCED",
  ADVANCED_REPLICATION = "CONNECTION_ADVANCED_REPLICATION",
  ADVANCED_PUBLICATION = "CONNECTION_ADVANCED_PUBLICATION",
  ADVANCED_SSL = "CONNECTION_ADVANCED_SSL",
  FILTERS = "FILTERS",
  DATA_OPTIONS_GENERAL = "CONNECTOR",
  DATA_OPTIONS_SNAPSHOT = "CONNECTOR_SNAPSHOT",
  DATA_OPTIONS_ADVANCED = "CONNECTOR_ADVANCED",
  RUNTIME_OPTIONS_ENGINE = "ADVANCED",
  RUNTIME_OPTIONS_HEARTBEAT = "ADVANCED_HEARTBEAT",
}

export enum FormStep {
  CONNECTOR_NAME = "ConnectorName",
  CONNECTION = "Connection",
  FILTER = "Filter",
  DATA_OPTION= "DataOption",
  RUNTIME_OPTION = "RuntimeOption",
  CUSTOM_PROPERTIES = "CustomProperties",
}
