apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: dbzui-kafka
spec:
  kafka:
    version: 2.5.0
    replicas: 5
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
      default.replication.factor: 2
      num.partitions: 10
      min.insync.replicas: 2
      auto.create.topics.enable: true
      log.segment.bytes: 536870912
      offsets.retention.minutes: 20160
      log.cleaner.delete.retention.ms: 2592000000
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 200Gi
          deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}