apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbzui-db-pg-volume-claim
  labels:
    app: dbzui-db-pg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: gp2
---
apiVersion: v1
kind: Service
metadata:
  name: dbzui-db-pg
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: dbzui-db-pg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbzui-db-pg
spec:
  selector:
    matchLabels:
      app: dbzui-db-pg
  replicas: 1
  template:
    metadata:
      labels:
        app: dbzui-db-pg
    spec:
      volumes:
      - name: dbzui-db-pg-volume
        persistentVolumeClaim:
          claimName: dbzui-db-pg-volume-claim
      containers:
      - name: dbzui-db-pg
        image: debezium/example-postgres:1.3
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        volumeMounts:
        - name: dbzui-db-pg-volume
          mountPath: /var/lib/postgresql
          subPath: data
