apiVersion: v1
kind: Service
metadata:
  name: dbzui-connect
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: dbzui-connect
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbzui-connect-config
data:
  BOOTSTRAP_SERVERS: dbzui-kafka-kafka-brokers:9092
  GROUP_ID: dbzui-connect
  CONNECT_PRODUCER_COMPRESSION_TYPE: lz4
  ADVERTISED_HOST_NAME: dbzui-connect
  ADVERTISED_PORT: "8083"
  CONFIG_STORAGE_TOPIC: dbzui-connect-configs
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "3"
  OFFSET_STORAGE_TOPIC: dbzui-connect-offsets
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "3"
  STATUS_STORAGE_TOPIC: dbzui-connect-status
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "3"
  KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbzui-connect
spec:
  selector:
    matchLabels:
      app: dbzui-connect
  replicas: 2
  template:
    metadata:
      labels:
        app: dbzui-connect
    spec:
      containers:
      - name: dbzui-connect
        image: debezium/connect:1.3
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: dbzui-connect-config
