name: Test Debezium UI Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/frontend-testing.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/frontend-testing.yml'

jobs:
  test:
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.14.2']
        os: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./ui
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        id: npm-cache
        uses: actions/cache@v2
        env:
            cache-name: cache-node-modules-v2
        with:
            path: |
                ~/.npm
                ~/.cache/Cypress
                node_modules
                */*/node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm install
          useLockFile: false
          working-directory: ./ui

      - name: Test Debezium UI Frontend
        run: npm run unit:test