name: Test Debezium UI Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/frontend-testing.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/frontend-testing.yml'

jobs:
  test:
    strategy:
      matrix:
        node: ['12.x', '14.x']
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./ui

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./ui
      - name: Test Debezium UI Frontend
        run: yarn run unit:test
      - name: Format
        run: yarn run format